### PR TITLE
added fake server demo link into #help section

### PR DESCRIPTION
**Pull request by ducin**
I have created fake server demos (a simple one and slightly advanced one) for the needs of the presentations and trainings I do. I couldn't find such resource out in the web.

Hope it'd be useful for Sinon.JS users. I'd be glad if you add it into the `#help` section

### CODE REVIEW

**Comment by ducin** [comment]
hello, any update on this one?

**Comment by ducin** [comment]
@cjohansen is there a chance that you merge the link in?

**Comment by cjohansen** [comment]
Sorry, hadn't seen this.

**Comment by ducin** [comment]
Thanks!

**Pull request merged**
